---
title: "R Notebook"
output: html_notebook
---

Package Setup
```{r}
library(DESeq2)
library(pheatmap)
library(enrichplot)
```

Matrix Creation
```{r}
random_ints <- sample(x=1:1000, size=50, replace=TRUE)
random_matrix <- matrix(data=random_ints, nrow=5, ncol=10)
```

Setting Column Names
```{r}
colnames(random_matrix) <- c("cond1", "cond2", "cond3", "cond4", "cond5", "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
colnames(random_matrix)
```

Defining Rows
```{r}
rownames(random_matrix) <- c("gene1", "gene2","gene3", "gene4", "gene5")
random_matrix
```

Computing fold change
```{r}
base <- c()
for (i in 1:5 ) {
  base <- c(base, random_matrix[,i]/random_matrix[,i+5])
}
fc <- matrix(data=base, nrow=5,ncol=5)
colnames(fc) <- c("cond1/ctrl1", "cond2/ctrl2", "cond3/ctrl3", "cond4/ctrl4", "cond5/ctrl5")
rownames(fc) <- c("gene1", "gene2","gene3", "gene4", "gene5")
fc
```


Final return matrix below showing the fold change for each gene between each condition and the corresponding control
```{r}
fc
```